
---
- name: junos_facts module
  hosts: juniper
  connection: local
  gather_facts: no
  tasks:

  ## This playbook will query facts and configuration in XML format on vsrx1
  ## The configuration will be automatically converted from XML to JSON

  - name: Collect device Facts and Configuration in XML
    junos_facts:
      gather_subset: all
      config_format: json
      provider: "{{ credential }}"
    register: result

  - name: Configuration in JSON (converted from XML)
    debug: var=result.ansible_facts.ansible_net_config
